### ISSUE TITLE
Moving dotted config files like in 2b does not work by default

### ISSUE THREAD

**Issue by JPustkuchen** [simlu/xmonad#4]
See:
http://superuser.com/questions/468255/how-to-mv-dot-files-without-including-the-parent-directory-on-linux-mac

> mv -v ~/downloads/xmonad-master/config/* ~/

Throws an error if dotglob is not enabled, because mv sees the directory empty.
You should execute
> shopt -s dotglob
before.

Please add that to your documentation. Additionally I used cp instead of mv to keep the files.

**Comment by simlu** [comment]
Interesting. Guess it must have been enabled by default for me...? Added it to the docs.

I used the mv command since I don't want ppl to have two local copies of the same file and then by accident edit the one that is not used.

Btw did you know you can do one-click pull requests by just editing the files? Github is pretty advanced there.
